### ISSUE TITLE
PS-Error during conversion

### ISSUE THREAD

**Issue by mighty-services** [theohbrothers/ConvertOneNote2MarkDown#1]
Thank you so much for your script. It´s amazing to read and I´m looking forward to converts my great amount of Onenote Notes to Markdown!

Unfortunately its showing up some errors during conversion when I use the normal Powershell-Window (in Admin Mode):
New-Object : Die COM-Klassenfactory für die Komponente mit CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} konnte
aufgrund des folgenden Fehlers nicht abgerufen werden: 80080005 Starten des Servers fehlgeschlagen (Ausnahme von
HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:353 Zeichen:16
     $OneNote = New-Object -ComObject OneNote.Application
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
     FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:356 Zeichen:5
     $OneNote.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.Hiera ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     FullyQualifiedErrorId : InvokeMethodOnNull

Ausnahme beim Aufrufen von "ReleaseComObject" mit 1 Argument(en):  "Der Objektverweis wurde nicht auf eine
Objektinstanz festgelegt."
In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:398 Zeichen:5
     [System.Runtime.Interopservices.Marshal]::ReleaseComObject($OneNo ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
     FullyQualifiedErrorId : NullReferenceException

Remove-Variable : Es kann keine Variable mit dem Namen "OneNote" gefunden werden.
In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:399 Zeichen:5
     Remove-Variable OneNote
     ~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (OneNote:String) [Remove-Variable], ItemNotFoundException
     FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

Thats the whole thing as screenshot:
![powershell_CQPqxemxLT](https://user-images.githubusercontent.com/71066192/92709705-6dea5700-f357-11ea-80cc-58f290fbb9fd.jpg)

Here some information about my system:
  - Windows 10 2004 (latest Updates from 10th September 2020 installed)
  - Onenote and Word Professional Plus 2016 (latest Updates from 10th September 2020 installed)
  - Cloned/downloaded the Master-Branch at 10th September 2020
  - used an absolute path
  - run Skript with default values (as show in the screenshot) AND with custom values (both gave out the same errors)
  - installed pandoc (verison 2.10.1) through chocolatey
  - installed recommended Onetastic Addin (Version 4.40 downloaded from the original Webpage)

**Comment by jcperezh** [comment]
> Thank you so much for your script. It´s amazing to read and I´m looking forward to converts my great amount of Onenote Notes to Markdown!
> 
> Unfortunately its showing up some errors during conversion when I use the normal Powershell-Window (in Admin Mode):
> New-Object : Die COM-Klassenfactory für die Komponente mit CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} konnte
> aufgrund des folgenden Fehlers nicht abgerufen werden: 80080005 Starten des Servers fehlgeschlagen (Ausnahme von
> HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
> In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:353 Zeichen:16
> $OneNote = New-Object -ComObject OneNote.Application
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : ResourceUnavailable: (:) [New-Object], COMException
> FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
> In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:356 Zeichen:5
> $OneNote.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.Hiera ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : InvalidOperation: (:) [], RuntimeException
> FullyQualifiedErrorId : InvokeMethodOnNull
> 
> Ausnahme beim Aufrufen von "ReleaseComObject" mit 1 Argument(en): "Der Objektverweis wurde nicht auf eine
> Objektinstanz festgelegt."
> In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:398 Zeichen:5
> [System.Runtime.Interopservices.Marshal]::ReleaseComObject($OneNo ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : NotSpecified: (:) [], MethodInvocationException
> FullyQualifiedErrorId : NullReferenceException
> 
> Remove-Variable : Es kann keine Variable mit dem Namen "OneNote" gefunden werden.
> In D:\Users\afrei\Downloads\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:399 Zeichen:5
> Remove-Variable OneNote
> ~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : ObjectNotFound: (OneNote:String) [Remove-Variable], ItemNotFoundException
> FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand
> 
> Thats the whole thing as screenshot:
> ![powershell_CQPqxemxLT](https://user-images.githubusercontent.com/71066192/92709705-6dea5700-f357-11ea-80cc-58f290fbb9fd.jpg)
> 
> Here some information about my system:
> 
> * Windows 10 2004 (latest Updates from 10th September 2020 installed)
> * Onenote and Word Professional Plus 2016 (latest Updates from 10th September 2020 installed)
> * Cloned/downloaded the Master-Branch at 10th September 2020
> * used an absolute path
> * run Skript with default values (as show in the screenshot) AND with custom values (both gave out the same errors)
> * installed pandoc (verison 2.10.1) through chocolatey
> * installed recommended Onetastic Addin (Version 4.40 downloaded from the original Webpage)

same here

**Comment by jcperezh** [comment]
resolved: I just ran Onenote also as Administrator

**Comment by mighty-services** [comment]
great! Thats it

> 
> 
> resolved: I just ran Onenote also as Administrator

**Comment by nixsee** [comment]
Sorry for getting to this so incredibly late... Looks like you folks solved the problem. I believe I mention in the Readme that you need to have Onenote and Powershell in the same mode - both Admin or both Normal.
