### ISSUE TITLE
Conversion fails with what appears to be a COM related error message

### ISSUE THREAD

**Issue by JohnWilliston** [theohbrothers/ConvertOneNote2MarkDown#102]
## Bug

Conversion fails with what appears to be a COM related error message.

## Expectation

I expected my dry run to go to completion.

## Discussion

The following is the output of the tool when I ran it:

Configuration:
dryRun: 2
notesdestpath: C:\Md
targetNotebook:
usedocx: 1
keepdocx: 1
docxNamingConvention: 2
prefixFolders: 2
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 2
keepescape: 1
newlineCharacter: 1
Convert-OneNote2MarkDown : Retrieving the COM class factory for component with CLSID
{DC67E480-C3CB-49F8-8232-60B0C2056C8E} failed due to the following error: 80080005 Server execution failed (Exception
from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
At C:\Src\ConvertOneNoteToMarkdown\ConvertOneNote2MarkDown-v2.ps1:1373 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Convert-OneNote2MarkDown : at New-OneNoteConnection, C:\Src\ConvertOneNoteToMarkdown\ConvertOneNote2MarkDown-v2.ps1:
line 510
at Convert-OneNote2MarkDown, C:\Src\ConvertOneNoteToMarkdown\ConvertOneNote2MarkDown-v2.ps1: line 1309
at <ScriptBlock>, C:\Src\ConvertOneNoteToMarkdown\ConvertOneNote2MarkDown-v2.ps1: line 1373
at <ScriptBlock>, <No file>: line 1
At C:\Src\ConvertOneNoteToMarkdown\ConvertOneNote2MarkDown-v2.ps1:1373 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Cleaning up...
Exiting.

## Environment

**Output of Configuration**

(see above)

**Output of `$PSVersionTable`**

For example:

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leojonathanoh** [comment]
@JohnWilliston thanks for the bug report! 

Could you provide your OS, and verify that OneNote Desktop 2016 is installed?

**Comment by leojonathanoh** [comment]
Do you happen to run this in a Windows Domain environment? Perhaps there are insufficient permissions to create the COM instance, see possible related: 

- https://forums.asp.net/t/2168811.aspx?+Discuss+Server+execution+failed+Exception+from+HRESULT+0x80080005+CO_E_SERVER_EXEC_FAILURE+
- https://stackoverflow.com/questions/29772500/powershell-cannot-create-outlook-com-object-from-command-prompt

**Comment by JohnWilliston** [comment]
> 
> 
> @JohnWilliston thanks for the bug report!
> 
> Could you provide your OS, and verify that OneNote Desktop 2016 is installed?

Here's what I got from PowerShell:

`PS C:\WINDOWS\system32> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19043  0`

The version of OneNote that shows is:

`Microsoft® OneNote® for Microsoft 365 MSO (16.0.14228.20216) 32-bit `

Is that the correct version? It's not the awful app version from the Microsoft Store. I thought it's the right version to work with your script, but please tell me if I'm wrong.

**Comment by leojonathanoh** [comment]
@JohnWilliston i dont see anything wrong with your setup. The version of onenote is a 2016 desktop version so it should run fine. 

This project needs bug reports like yours so we can narrow down exactly the difference between the environment of the users who run this tool fine and those who can't. 

Here's my onenote and environment


![20210826T140823-1629958104](https://user-images.githubusercontent.com/11932107/130910362-de565a81-0362-44da-8e77-6e8d61d9dd79.png)

![20210826T140913-1629958154](https://user-images.githubusercontent.com/11932107/130910407-e019562a-f389-4e30-8618-54c144c75deb.png)

Here's my OS version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

I'm also running under a user who is a local admin on Windows 1909 (`winver`). 

There only apparent difference is that mine is the 64bit version, and an older Windows 10 version. 

Perhaps you can try the 64bit version, and ensure run onenote under a local admin (no need UAC elevation, but has to be in the `Administrators` group in `mmc.exe`. Let me know if you need help with verifying your user is a local admin.

**Comment by JohnWilliston** [comment]
I can't easily try the 64-bit version because that will break compatibility with 32-bit tools I use with Office (e.g., MindManager). But I did find a fix for my issue: I ran OneNote as administrator. After that, I was able to complete a dry run with no trouble. I'm running it for real now and will let you know if I run into other issues.

**Comment by leojonathanoh** [comment]
@JohnWilliston yeah i'd think there should be no difference between the 32bit and 64bit versions. good to hear that the dry run worked :)

**Comment by leojonathanoh** [comment]
Just found there was a similar previous issue https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/7#issuecomment-792374398, with the same related link I posted in https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/102#issuecomment-906087583, with a clear explanation about the cause of `CO_E_SERVER_EXEC_FAILURE` error being about a mismatch in security contexts of powershell and onenote.

Putting this up for future readers.

**Comment by leojonathanoh** [comment]
@JohnWilliston did conversion go successfully? If so, I will close the issue.

**Comment by JohnWilliston** [comment]
Yes, what I converted completed successfully just fine. My only remaining issue is my own ignorance: I have to figure out how to get it to convert into MultiMarkdown format compatible with DEVONthink or find a tool to do that for me. Please do close the issue. Thanks so much for your help!

**Comment by leojonathanoh** [comment]
glad you got it working. you're welcome. :)
