### ISSUE TITLE
Attached files not inside an outline aren't included.

### ISSUE THREAD

**Issue by mikelehen** [theohbrothers/ConvertOneNote2MarkDown#117]
## Bug

File attachments in a OneNote page that aren't in an outline (text block) do not get imported into media/ or linked from the generated markdown.

## Expectation

All file attachments should be imported.

## Discussion

If you drag/drop a file into a OneNote page but don't put it inside of a text block (I guess OneNote calls this an "outline"?) then it won't be included.  E.g.:  
![image](https://user-images.githubusercontent.com/206364/147895888-34b21f10-b7aa-4ea3-a5ab-9771e2fb7aac.png)

When I import this I get the following markdown:
```
<<[testing.txt](media/testing.txt)>>



<<testing2.txt>>



<<testing3.txt>>
```

Note that testing2.txt and testing3.txt are not properly linked.

I see that the existing code https://github.com/theohbrothers/ConvertOneNote2MarkDown/blob/d572de0bf4c382919ce1e970753e97e646f00042/ConvertOneNote2MarkDown-v2.ps1#L868 is looking at `$pagexml.Page.Outline.OEChildren.OE` but it looks like these extra files end up in `$pagexml.Page.InsertedFile` instead.

I will provide a PR that attempts to address this.

## Environment

```Configuration:
dryRun: 1
notesdestpath: d:\drive\docs\Obsidian\Life
targetNotebook: MigrationTest
usedocx: 1
keepdocx: 2
docxNamingConvention: 2
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 255
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 1
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leojonathanoh** [comment]
Seems related with #127
