### ISSUE TITLE
--markdown-headings=atx throws error

### ISSUE THREAD

**Issue by DavidJLaw** [theohbrothers/ConvertOneNote2MarkDown#133]
## Bug

Pandoc throws unknown option error with --markdown-headings=atx 

which causes failure to convert

## Discussion

This is the default setting anyway, and the removal of this argument fixed the error for me 

## Environment

**Output of Configuration**

```powershell
Configuration:
dryRun: 1
notesdestpath: c:\Users\user\Documents\OneDriveMigration
targetNotebook:
usedocx: 1
keepdocx: 1
docxNamingConvention: 1
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 150
medialocation: 1
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 1
exportPdf: 1

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.25151.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.25151.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leojonathanoh** [comment]
@physical256 did pandoc just drop that `--markdown-headings=atx` support? Could you provide your pandoc version

**Comment by DavidJLaw** [comment]
pandoc.exe 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2

**Comment by leojonathanoh** [comment]
@physical256 it's been a while since i've used pandoc, so I can't remember which version I was on. Is yours a cutting edge version?

**Comment by DavidJLaw** [comment]
> @physical256 did pandoc just drop that `--markdown-headings=atx` support? Could you provide your pandoc version

Its strange really @leojonathanoh because it's still in the documentation but dropping it resolved the issue figure given atx is default

**Comment by leojonathanoh** [comment]
@physical256 that is strange. Perhaps they might have had a regression recently?

**Comment by DavidJLaw** [comment]
@leojonathanoh 2.17.1 is newest stable release looking at it so not a super old version but not cutting edge either

**Comment by DavidJLaw** [comment]
I wonder if its a bug in specific versions of pandoc let me update and see if it helps (although this is newest win installer version I can probably update with choco)

**Comment by leojonathanoh** [comment]
@physical256 i'm not familiar with pandoc myself so I've never really followed the releases, perhaps there was something they refactored between your version and the later versions. Probably you could try the later version  if it's not too much of a hassle.

**Comment by leojonathanoh** [comment]
sounds good.

**Comment by DavidJLaw** [comment]
> sounds good.

took me a minute to upgrade pandoc will try now :)

**Comment by DavidJLaw** [comment]
@leojonathanoh so pandoc 2.18 fixes this issue, suggest making requirements Pandoc = 2.7.2 | >=2.18

**Comment by leojonathanoh** [comment]
@physical256 thanks, glad it works for you. I"ll open a PR :)
