### ISSUE TITLE
The variable '$pageConversionConfigs' cannot be retrieved because it has not been set

### ISSUE THREAD

**Issue by AucaCoyan** [theohbrothers/ConvertOneNote2MarkDown#138]
## Bug

When I try to run the script, the console returns: `The variable '$pageConversionConfigs' cannot be retrieved because it has not been set.`

## Expectation

Either success on converting the notebook or an informed log about what has gone wrong

## Discussion

Hi! I love this app. Sadly I cannot make it work, When I run the script, I have this response from the shell, (after the config log):

```powershell
Notebooks to convert:
Auca's Notebook

Converting notebook 'Auca's Notebook'... (Ignoring deleted notes)

Building conversion configuration for Auca's Notebook [Notebook]
Ignoring empty Section Group:
Convert-OneNote2MarkDown : The variable '$pageConversionConfigs' cannot be retrieved because it has not been set.
At C:\Users\aucac\other-repos\ConvertOneNote2markdown\ConvertOneNote2MarkDown-v2.ps1:1474 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Convert-OneNote2MarkDown : at Convert-OneNote2MarkDown, C:\Users\aucac\other-repos\ConvertOneNote2markdown\ConvertOneNote2MarkDown-v2.ps1: line 1436
at <ScriptBlock>, C:\Users\aucac\other-repos\ConvertOneNote2markdown\ConvertOneNote2MarkDown-v2.ps1: line 1474
at <ScriptBlock>, <No file>: line 1
At C:\Users\aucac\other-repos\ConvertOneNote2markdown\ConvertOneNote2MarkDown-v2.ps1:1474 char:5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Cleaning up...
Exiting.
```

The script recognizes perfectly all my notebooks in onenote, but from there goes no further.

These are the setps I took:
1. I cloned the repo
2. installed pandoc with `choco install pandoc`
3. renamed config file to `config.ps1`
4. ran `.\ConvertOneNote2MarkDown-v2.ps1`

I googled about the error and found [this](https://stackoverflow.com/questions/51410527/mule-powershell-connector-the-variable-variable-name-cannot-be-retrieved) about a policy, tried, and didn't work either.
Am I doing something wrong? I also tested [alopezrivera/owo](https://github.com/alopezrivera/owo) but got the same result.

## Environment

**Output of Configuration**

```powershell
Configuration:
dryRun: 1
notesdestpath: c:\temp\notes
targetNotebook:
usedocx: 1
keepdocx: 1
docxNamingConvention: 1
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 32
medialocation: 1
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 1
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by leojonathanoh** [comment]
That is strange. The line responsible is `Tee-Object -Variable pageConversionConfigs`.

That means somehow, in your powershell session, `Tee-Object` is not populating the variable `$pageConversionConfigs`, for some reason. Perhaps, you have a powershell profile that overrides the behavior of `Tee-Object`, which is also aliased as `tee` in powershell.

**Comment by leojonathanoh** [comment]
See: 
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-5.1
- https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parameters_default_values?view=powershell-5.1

**Comment by AucaCoyan** [comment]
Hi! Sorry for the late response. I did some work that day and forgot about it for a long time.
Today I tried a couple of things and made it work. Apparently it wasn't the `$PROFILE` configuration, as I tried in 2 PCs, with PS 5.1 and 7.
I tried a couple of settings, among this as I remember:
* run as administrator
* open Microsoft One Note (Not the app from Microsoft App Store called OneNote for Windows 10)
* open word as an administrator
* deleting my $PROFILE config

And some combination made it work 🎉 ! I can't recall how I did it.
So, to the point. The issue is no troubling me anymore. You can leave it open, close it, or reopen as you wish.

Thanks for the help and keep going! This is an excellent repo 👍🏼

**Comment by leojonathanoh** [comment]
Thanks for sharing your solution. Seems like the error might have been a symptom of other errors thrown earlier in the script. Glad you have it solved anyway :)
