### ISSUE TITLE
When converting page with images, there's a line of text with width and height, which shouldn't be displayed? 

### ISSUE THREAD

**Issue by otterpro** [theohbrothers/ConvertOneNote2MarkDown#145]
## Bug

After conversion, when I opened the page with images, under each image, there's a line of text like ` {width="12.072916666666666in" height="6.65625in"}`.  It appears under every single image.  

## Expectation

I don't think there should be such text under the images.  I've got notes with lots of images, and it's annoying to have to delete the text manually.

## Discussion

This is my first time using it and everything else seems to have converted correctly.

## Environment

**Output of Configuration**

```my powershell Configuration:
$dryRun = 0
$notesdestpath = 'c:\tmp\notes'
$targetNotebook = ''
$usedocx = 1
$keepdocx = 1
$docxNamingConvention = 2
$prefixFolders = 1
$mdFileNameAndFolderNameMaxLength = 128
$medialocation = 1
$conversion = 'markdown-simple_tables-multiline_tables-grid_tables+pipe_tables'
$headerTimestampEnabled = 2
$keepspaces = 1
$keepescape = 1
$newlineCharacter = 1
$exportPdf = 1
```
```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by otterpro** [comment]
Oh, nevermind. I think that I just needed to choose another markdown flavor in `$conversion` for pandoc.

**Comment by wzajchow** [comment]
> Oh, nevermind. I think that I just needed to choose another markdown flavor in `$conversion` for pandoc.

Hi, which one did you choose to get rid of the additional line after images?

I have the same issue with default settings

**Comment by leojonathanoh** [comment]
@wzajchow try omitting some extensions using `-link_attributes-raw_html` (see [here](https://groups.google.com/g/pandoc-discuss/c/nXCbZpv5PpI)), so in `config.ps1`:

```powershell
$conversion = 'markdown-simple_tables-multiline_tables-grid_tables+pipe_tables-link_attributes-raw_html'
```

Haven't tried it myself though, let me know if it works for you.

**Comment by otterpro** [comment]
I just used this.
`$conversion = 'gfm+pipe_tables-raw_html'`

**Comment by nickchomey** [comment]
This command worked for me in a bash terminal to remove the `{width ... }` - including when it spans two/multiple lines (which was the most common case for me)

`grep -rlZ '\{width' . | xargs -0 sed -i -E ':a;N;$!ba;s/\{width[^\}]*?"\}//g'`
