### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by LynnXie00** [theohbrothers/ConvertOneNote2MarkDown#146]
## Bug

The code gives an error at line 570

 [xml]$hierarchy = ""
    $OneNoteConnection.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.HierarchyScope]::hsPages, [ref]$hierarchy)

with the error saying "Error HRESULT E_FAIL has been returned from a call to a COM component."

## Environment

**Output of Configuration**

```powershell
Configuration:
dryRun: 0
notesdestpath: C:\00 OnenoteLocal\learning notes
targetNotebook:
usedocx: 2
keepdocx: 1
docxNamingConvention: 1
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 200
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_ta
bles
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 2
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by leojonathanoh** [comment]
Please use powershell 7.0 and below, i believe powershell 7.1 and above is not supported from my own testing. See https://github.com/theohbrothers/ConvertOneNote2MarkDown#requirements

**Comment by leojonathanoh** [comment]
In particular, see these lines:

https://github.com/theohbrothers/ConvertOneNote2MarkDown/blob/3a83d5207b15ee992d0913e3c46f78690c7182fd/ConvertOneNote2MarkDown-v2.ps1#L538-L543

I will add this to the FAQ since this doesn't seem clear in the readme.

**Comment by leojonathanoh** [comment]
You can download powershell `7.0.13` here: https://github.com/PowerShell/PowerShell/releases/v7.0.13, scroll down to `Assets` and download `PowerShell-7.0.13-win-x64.zip`, extract it to say `C:\PowerShell-7.0.13-win-x64`, and run `C:\PowerShell-7.0.13-win-x64\pwsh.exe` in the unzipped directory. That way it won't mutate your existing powershell `7.3` in `PATH`. Please let me know if it works, so i can add this to the readme.

**Comment by felipemeres** [comment]
> You can download powershell `7.0.13` here: https://github.com/PowerShell/PowerShell/releases/v7.0.13, scroll down to `Assets` and download `PowerShell-7.0.13-win-x64.zip`, extract it to say `C:\PowerShell-7.0.13-win-x64`, and run `C:\PowerShell-7.0.13-win-x64\pwsh.exe` in the unzipped directory. That way it won't mutate your existing powershell `7.3` in `PATH`. Please let me know if it works, so i can add this to the readme.

I was getting `Error HRESULT E_FAIL has been returned from a call to a COM component.` and using version 7.0.13 fixed it for me.

**Comment by leojonathanoh** [comment]
@fmeres thanks for the feedback. I'll add this to readme.

**Comment by LynnXie00** [comment]
I downloaded the powershell 7 but my VS code's powershell extension somehow won't load with powershell 7... I guess this version is too old for it . You can add in readme not to use VS code anymore......

So I added the following to the end of the code (after  Convert-OneNote2MarkDown @params) and run the code directly using the powershell 7 exe, so at least I can see the log if there are any errors.

    Write-Host "Press any key to continue..."
    $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
    
 Now the code seems running fine. I'll update you later when I see the output.

**Comment by leojonathanoh** [comment]
> I downloaded the powershell 7 but my VS code's powershell extension somehow won't load with powershell 7... I guess this version is too old for it . You can add in readme not to use VS code anymore......

By default, VSCode Powershell extension launches `Windows PowerShell (x64)` or `Windows PowerShell (x86)`, i.e. Powershell 5.1, which is already included in Windows 10 / 11. So there is no need to install Powershell 6 or 7 at all actually.

But if one insists on using Powershell 6 / 7,  one needs to add something like this in VSCode `settings.json` to launch a specific version of `pwsh.exe`. In VSCode, press `F1 > Preferences: Open Use Settings (JSON)` which opens `settings.json`, paste the following and save the file:

```json
  "powershell.powerShellAdditionalExePaths": {
    "Powershell 7.0.13": "C:\\PowerShell-7.0.13-win-x64\\pwsh.exe"
  },
```

Then `F1 > Powershell: Show Session Menu > Switch to: Powershell 7.0.13` to start Powershell 7.0.13.

I agree that the readme includes a lot of unnecessary information by the very first author of this fork not directly related with the conversion itself. I'll see what we can do to improve the docs.

> So I added the following to the end of the code (after Convert-OneNote2MarkDown @params) and run the code directly using the powershell 7 exe, so at least I can see the log if there are any errors.

> Now the code seems running fine. I'll update you later when I see the output.

Thanks, I appreciate your feedback very much :)
