### ISSUE TITLE
Exception: Exception calling "Publish" with "4" argument(s): "0x80042006"

### ISSUE THREAD

**Issue by LynnXie00** [theohbrothers/ConvertOneNote2MarkDown#149]
## Bug

Failure to export to word, PowerShell gives an error saying "Exception: Exception calling "Publish" with "4" argument(s): "0x80042006""

## Expectation

During the conversion, OneNote notes should be exported to Word and then converted to Md.

## Discussion
The conversion worked well at the beginning, then this error alert started to happen for each document. After I turned off the codes, I found that there are many word processes opened in the task manager (I bet there are over 30 processes... see the image below). It is normal? Could it be the reason why this error occurs? 

[task manager screenshot](https://i.ibb.co/wZH24H8/Snipaste-2023-02-04-17-53-06.png)

## Environment
I am using Office 365 and use a notebook folder in onedrive, inside of it is the internet shortcut pointing to the onenote online. I tried to run the code in a local folder with .one files, but it won't work. 

**Output of Configuration**

```powershell
Configuration:
dryRun: 0
notesdestpath: C:\Users\verac\OneDrive\Documents\Notebooks
targetNotebook:
usedocx: 2
keepdocx: 1
docxNamingConvention: 1
prefixFolders: 1
mdFileNameAndFolderNameMaxLength: 200
medialocation: 2
conversion: markdown-simple_tables-multiline_tables-grid_tables+pipe_tables
headerTimestampEnabled: 1
keepspaces: 1
keepescape: 1
newlineCharacter: 2
exportPdf: 1
```

**Output of `$PSVersionTable`**

```powershell
PS > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.13
PSEdition                      Core
GitCommitId                    7.0.13
OS                             Microsoft Windows 10.0.22622
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by leojonathanoh** [comment]
Hey again, did some pages convert successfully before this happened?

**Comment by leojonathanoh** [comment]
See possibly related: https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/112#issuecomment-1100757008

**Comment by LynnXie00** [comment]
> Hey again, did some pages convert successfully before this happened?

Yes.... I suspect that's because windows are fine with only a few Word processes open at the beginning, but later when there were too many, the system won't respond anymore. My Onenote froze, and I could not shut down all the Word processes either from task management. I had to restart my computer.

**Comment by leojonathanoh** [comment]
Hmm it's strange, this shouldn't happen, because it should convert only one document at one time, meaning only one `winword.exe` should be running at any time. There might be an issue with the compatibility of the Word and OneNote versions. Did you make sure to leave your system alone during the conversion?

**Comment by LynnXie00** [comment]
> 

I did.... Let me try it again with the suggestions in that [112 thread](https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/112#issuecomment-1100757008) and open both word and onenote as administrator....

**Comment by leojonathanoh** [comment]
sure, let me know how it goes.

**Comment by LynnXie00** [comment]
Nevermind, I ran out of disk space....But I had 11G available before it....not sure what happened....now I have again many many word processes in the background....
_________________
Hmmm, right now the Powershelll, Word, and Onenote are all open with the administrator, this 0x80042006 did not happen anymore, but after successfully converting 315 pages, all the rest pages end up having the following issues:

```
Convert-OneNotePage: C:\Users\verac\OneDrive - University of Toledo\Documents\GitHub\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1387
Line |
1387 |  … onConfigs | Convert-OneNotePage -OneNoteConnection $OneNote -Config $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to convert page: archive\Master\Mid-term-review. Exception: Error while publishing page to docx file
     | C:\Users\verac\OneDrive\Documents\Notebooks\learning-notes\docx\{A55A2835-72D0-0604-1591-C003FF22417F}{1}{E195112547914313399952187327802832395910651}-1553727361.docx. Exception: Exception calling "Publish" with "4" argument(s): "Server execution failed  Server execution failed "

```

It is not what in your Q & A stated due to Mismatch in security contexts in my case.... so I have no idea now....

I wonder, is there a limit for how many pages can be converted each time for the Onenote API used?

**Comment by LynnXie00** [comment]
> Nevermind, I ran out of disk space....But I had 11G available before it....not sure what happened....now I have again many many word processes in the background....
> 
> Hmmm, right now the Powershelll, Word, and Onenote are all open with the administrator, this 0x80042006 did not happen anymore, but after successfully converting 315 pages, all the rest pages end up having the following issues:
> 
> ```
> Convert-OneNotePage: C:\Users\verac\OneDrive - University of Toledo\Documents\GitHub\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1387
> Line |
> 1387 |  … onConfigs | Convert-OneNotePage -OneNoteConnection $OneNote -Config $ …
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Failed to convert page: archive\Master\Mid-term-review. Exception: Error while publishing page to docx file
>      | C:\Users\verac\OneDrive\Documents\Notebooks\learning-notes\docx\{A55A2835-72D0-0604-1591-C003FF22417F}{1}{E195112547914313399952187327802832395910651}-1553727361.docx. Exception: Exception calling "Publish" with "4" argument(s): "Server execution failed  Server execution failed "
> ```
> 
> It is not what in your Q & A stated due to Mismatch in security contexts in my case.... so I have no idea now....
> 
> I wonder, is there a limit for how many pages can be converted each time for the Onenote API used?

Okay, I found 4G of diagnostic file from Word....I hope it's not because each failed conversion will generate a diagnostic file....

**Comment by leojonathanoh** [comment]
> I wonder, is there a limit for how many pages can be converted each time for the Onenote API used?

No limit. It should not fail half way unless there is something else going on. It's a strange error. Perhaps you can try to free up disk space.

> Okay, I found 4G of diagnostic file from Word....I hope it's not because each failed conversion will generate a diagnostic file.... 

That is strange, never knew each failed conversions will fill up the disk with diagnostic files. I'd suggest you use Disk Cleanup to make some free space. Let me know how it goes.

**Comment by leojonathanoh** [comment]
Found https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/11#issuecomment-835081893, please try to turn off Windows Defender, perhaps detecting suspicious activity and blocking the conversion. Try adding an exception for `pandoc.exe` first and convert. If that fails again, just flip off all the switches, you can always turn it back on after the conversion.

**Comment by LynnXie00** [comment]
> Found [#11 (comment)](https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues/11#issuecomment-835081893), please try to turn off Windows Defender, perhaps detecting suspicious activity and blocking the conversion. Try adding an exception for `pandoc.exe` first and convert. If that fails again, just flip off all the switches, you can always turn it back on after the conversion.

I have found out why. And my notes are all converted now. This script seems to be imcompatible with the zotero's word plugin. People who use zotero should disable zotero plugin. Maybe other citation plugins are also incompatible. 

Also, I noticed that this is not in the readme: the code can only convert notebooks that are **currently open in onenote.** 

I gave powershell and word the administrator's authority, but not Onenote. If you open onenote in administrator, windows will say "onenote cannot open file because onenote is open as administrator " Both onenote and word are open before running the script.

**Comment by leojonathanoh** [comment]
> I have found out why. And my notes are all converted now. This script seems to be imcompatible with the zotero's word plugin. People who use zotero should disable zotero plugin. Maybe other citation plugins are also incompatible.

Thanks for the information. I'll add this to the readme.

> Also, I noticed that this is not in the readme: the code can only convert notebooks that are currently open in onenote.

You are right, we probably missed that. I think the reason why all the authors didn't think of putting this, is because they assume users are going to convert all their notebooks they are using (all of which are open in OneNote). Where are you other notebooks which are not open in OneNote then?

> I gave powershell and word the administrator's authority, but not Onenote. If you open onenote in administrator, windows will say "onenote cannot open file because onenote is open as administrator " Both onenote and word are open before running the script.

Never knew that you couldn't open OneNote as Administrator. Many others actually claimed that opening OneNote as Admin solved their issue, and I've never heard of any of them getting an error. If you look through the past issues with keyword "Administrator" [here](https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues?q=is%3Aissue+administrator+is%3Aclosed), many claim to have been able to do so. Perhaps it might be your specific version of OneNote? The general consensus is that Powershell / VSCode, and OneNote have to be run as Administrator. 

Glad you managed to solve it anyway, and I will include this info in the readme.

**Comment by LynnXie00** [comment]
> Where are you other notebooks which are not open in OneNote then?

All my notes were in the same folder, but only the open ones were displayed at the beginning of the scripts and were converted.

>If you look through the past issues with keyword "Administrator" [here](https://github.com/theohbrothers/ConvertOneNote2MarkDown/issues?q=is%3Aissue+administrator+is%3Aclosed), many claim to have been able to do so. Perhaps it might be your specific version of OneNote?

I know, I'm using Office 365 offered by my school (see[ this screenshot](https://i.ibb.co/sPzJ36c/Snipaste-2023-02-05-12-15-25.png)). So it should be the latest. This alert doesn't always happen, but when it says "OneNote cannot open file because onenote is open as administrator, "  then I close and reopen Onenote without administrator authority will solve the issue.

**Comment by leojonathanoh** [comment]
> All my notes were in the same folder, but only the open ones were displayed at the beginning of the scripts and were converted.

Basically, the script only converts notebooks which has been "imported" and open in the local instance of OneNote (i.e. what we mean by "open") , e.g.  `File > Open`. Notebooks which haven't been "imported" will  not be converted, even if they exist in the Cloud e.g. OneDrive, Teams notebooks. I think this could be clearer in the readme.

> I know, I'm using Office 365 offered by my school (see[ this screenshot](https://i.ibb.co/sPzJ36c/Snipaste-2023-02-05-12-15-25.png)). So it should be the latest. This alert doesn't always happen, but when it says "OneNote cannot open file because onenote is open as administrator, " then I close and reopen Onenote without administrator authority will solve the issue.

That is useful to know. I'll add this in the readme.
