### ISSUE TITLE
How to import an HTML page in OneNote?

### ISSUE THREAD

**Issue by it19862** [theohbrothers/ConvertOneNote2MarkDown#15]
How to import an HTML page in OneNote?

I understand that the question is not for this place, but still, can someone suggest some solution.…

**Comment by nixsee** [comment]
Like how to import a website into onenote?

**Comment by it19862** [comment]
@nixsee 
I am interested in moving both the site and a separate page by link...

### Task-1. Move the site.
**Decision**. (as I see it)
         - Parse or download the site to the local disk of the computer.
	- in the applicationt insert a link to the page;
	- in the application, select a place in the notebook tree where you want to insert the pages 
	HTML;
	- The user starts the move(or copy) operation);
	- Result: the pages are displayed in OneNote in accordance with the format;
	
### Task-2. Move one or more pages from different sites. 
**Decision.** (as I see it)
	- insert a list of links in the app;
	- in the application, select a place in the notebook tree where you need to insert HTML pages;
	- The user starts the move(or copy) operation.);
	- Result: Pages are displayed in OneNote with the original formatting saved;

**Question.**
	How to implement all or part of the described functionality?

**Note.**
 I own C#. 
 I use
- Win-7x64;
  - OneNote - 2016.

Sorry I didn't write the details right away...

**Comment by nixsee** [comment]
Sorry, but i dont understand what youre trying to do. Anyway, this is the wrong place to be asking. Check out stackoverflow, reddit, etc... 

https://www.httrack.com/ this software might help you with downloading the sites though. The onenote web clipper https://www.onenote.com/clipper should help as well. 

Good luck
