### ISSUE TITLE
"Could not locate pandoc.exe. Please ensure pandoc is installed."

### ISSUE THREAD

**Issue by ovnis82** [theohbrothers/ConvertOneNote2MarkDown#159]
Hello,

I have installed pandoc (C:\Program Files\Pandoc\pandoc.exe) +  antivrus disabled + set-ExecutionPolicy -ExecutionPolicy Unrestricted, but I have this error message: 

PS C:\Windows\System32\ConvertOneNote2MarkDown> .\ConvertOneNote2MarkDown-v2.ps1
Get-Command : Le terme «pandoc.exe» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou
programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès
est correct et réessayez.
Au caractère C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:27 : 12
+     if (! (Get-Command -Name 'pandoc.exe') ) {
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pandoc.exe:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

Convert-OneNote2MarkDown : Could not locate pandoc.exe. Please ensure pandoc is installed.
Au caractère C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1428 : 5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Convert-OneNote2MarkDown : à Validate-Dependencies,
C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1 : ligne 28
à Convert-OneNote2MarkDown, C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1 : ligne 1355
à <ScriptBlock>, C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1 : ligne 1428
à <ScriptBlock>, <Aucun fichier> : ligne 1
Au caractère C:\Windows\System32\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:1428 : 5
+     Convert-OneNote2MarkDown @params
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Convert-OneNote2MarkDown

Cleaning up...
Exiting.

Thx!

**Comment by leojonathanoh** [comment]
It's strange. Does `pandoc.exe` run using Command Prompt?

**Comment by ovnis82** [comment]
I have moved ConvertOneNote2MarkDown from system32 to the dekstop. Fixed.

**Comment by leojonathanoh** [comment]
good to know that it can't work in `system32` :)
