### ISSUE TITLE
Reopen #5 Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].

### ISSUE THREAD

**Issue by slappycat2** [theohbrothers/ConvertOneNote2MarkDown#16]
Hi Nixsee,
I'm not sure why this was closed, as the previous OP never said it was resolved. 
I'm running into the exact same issue, tried it various ways, but currently, Office 2016-Desktp, and both VS Code and OneNote running as Admin.
------------------------------------------------------------------------
Enter the (preferably empty!) folder path (without trailing backslash!) that will contain your resulting Notes structure. ex. 'c:\temp\notes'
Entry: D:\docs1

-----------------------------------------------

-----------------------------------------------
1: Create new .docx files - Default
2: Use existing .docx files (90% faster)
Entry:

-----------------------------------------------
1: Discard intermediate .docx files - Default
2: Keep .docx files
Entry: 2

-----------------------------------------------
1: Create folders for subpages (e.g. Page\Subpage.md)- Default
2: Add prefixes for subpages (e.g. Page_Subpage.md)
Entry:

-----------------------------------------------
1: Images stored in single 'media' folder at Notebook-level (Default)
2: Separate 'media' folder for each folder in the hierarchy
Entry:

Select conversion type
-----------------------------------------------
1: markdown (Pandoc) - Default
2: commonmark (CommonMark Markdown)
3: gfm (GitHub-Flavored Markdown)
4: markdown_mmd (MultiMarkdown)
5: markdown_phpextra (PHP Markdown Extra)
6: markdown_strict (original unextended Markdown)
Entry: :
-----------------------------------------------
1: Clear double spaces in bullets - Default
2: Keep double spaces
Entry:
-----------------------------------------------
1: Clear '\' symbol escape character from files
2: Keep '\' symbol escape
Entry:
InvalidOperation: D:\!foam\ConvertOneNote2MarkDown\ConvertOneNote2MarkDown-v2.ps1:361:31
Line |
 361 |  … erarchy("", [Microsoft.Office.InterOp.OneNote.HierarchyScope]::hsPage …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [Microsoft.Office.InterOp.OneNote.HierarchyScope].

**Comment by nixsee** [comment]
There's no need to create another issue for this here. I have replied to your other comment on the original issue (#5 )
