### ISSUE TITLE
Ordered list

### ISSUE THREAD

**Issue by sGhadir** [theohbrothers/ConvertOneNote2MarkDown#160]
## Bug

Ordered lists from onenote have double spaces after conversion. When looking at the intermediate created doc files, it seems that there is a break after each line. I tried but I have no idea how to solve this. See image: 

1. **Onenote:**
![image](https://user-images.githubusercontent.com/105933678/233829572-eac835e7-4c6d-4729-b2a4-5d98fb3fa3c2.png)

2. **Intermediate DOCX:**
![image](https://user-images.githubusercontent.com/105933678/233829610-1bb6bf62-1261-4968-9c2d-11ad2ecbcaff.png)
![image](https://user-images.githubusercontent.com/105933678/233829616-4b206945-db32-46c5-b307-09e4a6530e47.png)

2. **Markdown output:**
![image](https://user-images.githubusercontent.com/105933678/233829638-cba7061f-f641-44ae-bfa1-6ed12db491ca.png)

I have not currently found  a way to solve this, and it seems to me that I will have to change all ordered lists to bullet lists before doing the conversion. Is there any way this can be solved so that the lists don't have spaces?

Thanks

**Comment by leojonathanoh** [comment]
sorry, was away a few days. Looking at my past notes that were converted with this script, you are right that there is a newline between ordered-list items. I think this is valid markdown syntax as determined by most markdown linters of various markdown flavors. 

EDIT: stale, see next reply

<details>

But if you want to remove the extra newline, you will need to use add a regex search and replacement, something like the `keepspaces` one [here](https://github.com/theohbrothers/ConvertOneNote2MarkDown/blob//v2.19.2/ConvertOneNote2MarkDown-v2.ps1#L929-L949). So, add one mor hashtable under that hashtable:

```powershell
                            if ($config['keepspaces']['value'] -eq 1 ) {
                                @{
                                    description = 'Clear double spaces from ordered lists'
                                    replacements = @(
                                        @{
                                            searchRegex = '\r*\n\r*\n(\s*)[a-zA-Z0-9]+\. '
                                            replacement = "`n`$1- "
                                        }
                                    )
                                }
                            }
```

</details>

Let me open a PR with a unit test to see if this works.

**Comment by leojonathanoh** [comment]
please try out my new PR, hope it works for you. If it works, will merge it to master.

**Comment by sGhadir** [comment]
Thank you :) I will try it as soon as I get the chance and get back to you.

**Comment by leojonathanoh** [comment]
sure :)

**Comment by sGhadir** [comment]
Sorry for my late reply. This works perfectly thank you very much! You just saved me hours of tedious work

**Comment by leojonathanoh** [comment]
glad to help :)
