### ISSUE TITLE
File path with spaces don't work

### ISSUE THREAD

**Issue by fromSmolsoft** [theohbrothers/ConvertOneNote2MarkDown#163]
## Bug

$notesdestpath = '...'   can't work with file-path that includes space.
It passes path without double quotations `""` to the pandoc. 
    
Pandoc thinks of part of the path after the space as param. 
e.g. `'c:\My Notes\notes'` or "c:\My Notes\notes" or `'"c:\My Notes\notes"'`   Will result in creating *.docx but pandoc will report it can't find file located at `c:\My`   
 
## Expectation

Should work regardless of space in file-path.   
probably it needs to pass `"path"` to pandoc wrapped in double quotations.

## Environment

PowerShell-7.0.13-win-x64

**Comment by leojonathanoh** [comment]
I can add support for this. 

>  probably it needs to pass "path" to pandoc wrapped in double quotations.

yes. But Powershell has a long known issue with passing double quotes to commands without escaping with `\`. I'll try to see what I can do to support spaces. In the meanwhile, please use a path without spaces.

**Comment by leojonathanoh** [comment]
Hey @fromSmolsoft, I've opened #165, could you try with spaces in `$notesdestpath` and tell me whether it works?

**Comment by fromSmolsoft** [comment]
Fix at #165  works.
