### ISSUE TITLE
Errors and only getting word files (no md)

### ISSUE THREAD

**Issue by Harkens** [theohbrothers/ConvertOneNote2MarkDown#17]
I have no idea what I'm doing wrong (it's the first I've used Onetastic and Pandoc, and probably the first time I've run a script like this on Powershell) but I followed the instructions (including opening both powershell and OneNote on administrator and running the security bypass) and tried it a few times and the results are the same. I have almost no coding knowledge and googling what might work to fix it hasn't worked out (I initially had spaces in one of the folders and did both CD "" and just straight up removing the spaces in the folder name to navigate to the proper folders, but beyond that I couldn't figure out what still needed to be done).

Below is an example of the error I got (it seems to have happened with every OneNote page):

![REDACTED Troubleshooting OneNote to Obsidian conversion 1](https://user-images.githubusercontent.com/86947912/124432296-0c8eeb00-dda4-11eb-8da3-cfbff32cea3d.jpg)

![REDACTED Troubleshooting OneNote to Obsidian conversion 2](https://user-images.githubusercontent.com/86947912/124430478-ccc70400-dda1-11eb-92d6-5970e611de75.jpg)

Not sure what information would be relevant but I have the copy of this repository saved in Desktop\ProgramsAndOtherInstalls and the folder I wanted the .md files to go to is Documents\OneNoteExport2Obsidian. Within the later folder the script made a folder for each notebook I had on OneNote (the page "Prologue" is from my OneNote notebook "recover") and within those are three folders: "docx" where the .docx files of all my OneNote pages were stored, and two folders named after the main sections I have in my "recover" notebook. Those two sections have folders that correspond to their subsections but all the folders are empty except for one document I had saved into one of my OneNote pages.

Just in case this was important, the options I chose were the following:
![REDACTED Troubleshooting OneNote to Obsidian conversion 3](https://user-images.githubusercontent.com/86947912/124434221-30533080-dda6-11eb-960a-dc651e6638fe.jpg)

**Comment by Iseultsa** [comment]
![erreur script](https://user-images.githubusercontent.com/87090013/124805088-07a77400-df29-11eb-9f08-9a71d2ee2942.jpg)
This is partly in French but I compared it with the user Harkens's images and the text is the same, so I must be doing something wrong. I also have not coding experience and simply tried to follow the instructions. It created folders but not the markdown files.

**Comment by nixsee** [comment]
@Harkens Thanks for being thorough. It doesn't seem like an issue with OneNote, Powershell, Admin mode, etc... 

The first image you posted says something about CommonMark not working. Have you tried running this with Pandoc Markdown (option 1 in the Conversion Type prompt), or other conversion methods?

**Comment by Harkens** [comment]
@nixsee Everything ran smoothly once I tried Pandoc Markdown instead. Thank you!

**Comment by nixsee** [comment]
@Harkens Good to hear. 
@Iseultsa I'm guessing you have a similar issue.

**Comment by Iseultsa** [comment]
@nixsee I ran it again today with Pandoc Markdown and this time I choose to save the word files. I do have word files now, but I don't have anything else except empty folders. Again the text in the image is in French, but maybe you can see something here that can 
![error](https://user-images.githubusercontent.com/87090013/125829787-c9590f92-3cd9-4cc8-a8d6-baa9fcd0d6b9.jpg)
