### ISSUE TITLE
FR: Convert img tags to markdown image tags (Obsidian support)

### ISSUE THREAD

**Issue by tehguitarist** [theohbrothers/ConvertOneNote2MarkDown#181]
## Current

Images are put in `<img>` tags

## Expectation

Images are coded in markdown format so conversion/plugins (which doesn't work anymore) aren't needed.

## Discussion

Hopefully should be an easy conversion to add a flag for. I couldn't find a good way to adjust height/width though, but here's an example of what to convert:

HTML style
`<img src="../media/Products Novastar-Info-image1.png" alt="alt text" title="title"/>`

MD style
`![alt text](media/Products%20Novastar-Info-image1.png "title")`

This assumes all media is in the media folder of the root directory for the exported OneNote file. Spaces are replaced by %20, otherwise should be ok. I could probably write a python script to parse all of this, but I can see this being useful for people.

**Comment by leojonathanoh** [comment]
@tehguitarist see Step 10 of [usage](https://github.com/theohbrothers/ConvertOneNote2MarkDown#usage). Use a `$conversion` value of your liking.

**Comment by tehguitarist** [comment]
Thanks Leo, I'm currently running with both suggested $conversion scripts, and I saw that in the original issue for one, the user needed to use a plugin (which no longer works) to make img tags working, unless there is another way of formatting? I can dig through Pandocs too though.

**Comment by leojonathanoh** [comment]
Yes, in #150 it was found that `$conversion = 'markdown_mmd-simple_tables-multiline_tables-grid_tables+pipe_tables-mmd_link_attributes'` is the best overall setting for Obsidian, but you may prefer github flavoured markdown with `-mmd_link_attributes` if you want `<img>` to be converted to `![]` in markdown.

**Comment by tehguitarist** [comment]
Thanks kindly, the github format might do the trick for now. Appreciate the pointers!
