### ISSUE TITLE
Sponsor the work ?

### ISSUE THREAD

**Issue by Sabin-Gheorghiu** [theohbrothers/ConvertOneNote2MarkDown#182]
First I just wanted to say thank you for the time to make this project! 
In transitioning from OneNote to Joplin (going full open source) this has been instrumental (I am a note hoarder).

I would really like support in some way considering the time this has saved me (doing 20 notebooks of 40+ subsections manually would have been really iffy).

Could I buy you guys a coffee/ Github Sponsor this project? 

Great work and again thank you!

**Comment by leojonathanoh** [comment]
Hey @Sabin-Gheorghiu, thank you for you kind words 😄 I'm glad this helped you.

While it was quite a bit of work to get this things to convert my 10 to 15 or so notebooks (several gigabytes, about two years ago), it works nicely as a one-off script, which we thought would be useful for anyone else who needed help with this. 

At the moment, we do not accept donations. The very best thing you could do for us is to help others who may not know how to own their notes without being tied to a sole application 😃 Thank you once again! 😄
