### ISSUE TITLE
UTF8 Issue

### ISSUE THREAD

**Issue by mighty-services** [theohbrothers/ConvertOneNote2MarkDown#2]
I used all 6 coding methods but non of the could handle the UTF8 coding.
Teh DOCX-Files where okay, but the step to the MDfiles killed the special characters like ä,ö,ü etc.

Is there a way to fix that?

**Comment by mighty-services** [comment]
No way??

**Comment by rab-bit** [comment]
@mighty-services I've corrected it on [ConvertOneNote2MarkDown4Obsidian](https://github.com/rab-bit/ConvertOneNote2MarkDown4Obsidian/blob/master/docs/README.md)
Check it out

**Comment by nixsee** [comment]
Sorry for being so late to this. Strange that you don't get UTF 8 - I get it with mine. Maybe something to do with system defaults. I see @rab-bit's contributions now and will merge them soon after we discuss them a bit.
