### ISSUE TITLE
Multiple 'being used by another process' errors

### ISSUE THREAD

**Issue by doodlewhale** [theohbrothers/ConvertOneNote2MarkDown#3]
Errors while: 'renaming image file path references', 'set-content', 'while clearing double spaces', etc.

An example:
`Error while renaming image file name references to 'image59.png' for file 'Note Name': The process cannot access the file 'D:\folder\Note Name.md' because it is being used by another process.`

**Comment by nixsee** [comment]
Sorry for being so late to this. If you never figured this out, I suspect it has something to do with those files being open elsewhere - if they're being used with a VS Code markdown extension, Obsidian or another application, have you closed the application when doing exports?
