### ISSUE TITLE
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.

### ISSUE THREAD

**Issue by kamilNope** [theohbrothers/ConvertOneNote2MarkDown#6]
Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\GIT\ConvertOneNote2MarkDown-master\ConvertOneNote2MarkDown-v2.ps1:352 char:21
 if (Test-Path -Path $notesdestpath) {
                   ~~~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
     FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

**Comment by nixsee** [comment]
Have you entered a file path for the folder where you want your notes to go? e.g. 'C:\Users\Kamil\OnenoteMarkdown'
