### ISSUE TITLE
Retrieving the COM class factory for component failed

### ISSUE THREAD

**Issue by ezjones** [theohbrothers/ConvertOneNote2MarkDown#7]
I am running Win10 and Onenote 2016. Don't know what's causing this.
```
New-Object : Retrieving the COM class factory for component with CLSID {DC67E480-C3CB-49F8-8232-60B0C2056C8E} failed
due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005
(CO_E_SERVER_EXEC_FAILURE)).
At C:\Users\ez\Downloads\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote
2MarkDown-v2.ps1:721 char:16
+     $OneNote = New-Object -ComObject OneNote.Application
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Users\ez\Downloads\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote2MarkDown4Obsidian-master\ConvertOneNote
2MarkDown-v2.ps1:724 char:5
+     $OneNote.GetHierarchy("", [Microsoft.Office.InterOp.OneNote.Hiera ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by emesar** [comment]
@ezjones I had the same issue - this thread helped me out: https://stackoverflow.com/questions/29772500/powershell-cannot-create-outlook-com-object-from-command-prompt

Specifically:

> `CO_E_SERVER_EXEC_FAILURE` in case of Outlook means the calling app and the COM server are running in different security contexts. If the command prompt is running with elevated privileges, either make sure Outlook is started with elevated privileges as well or that it does not run at all when your code is executed - this way Outlook will be started by your code and it will run with the same elevated privileges.

Meaning, you should be running both Powershell and OneNote from the same security context (either as Administrator or your user). Once I did that, everything worked like a charm.

**Comment by nixsee** [comment]
This is already addressed in the readme. Closing issue.
