### ISSUE TITLE
Trying to get in contact with you

### ISSUE THREAD

**Issue by m0r4h3u5** [theohbrothers/ConvertOneNote2MarkDown#8]
Please DM via [Twitter](https://twitter.com/m0r4h3u5) or leave a comment on one of the pages of my web site at [https://reevolution.earth](https://reevolution.earth) as I'd like to chat with you. Thanks

**Comment by m0r4h3u5** [comment]
Tagging you @nixsee

**Comment by nixsee** [comment]
I don't use twitter. Feel free to chat here or message me on whatever platform you found me on.

**Comment by m0r4h3u5** [comment]
Thanks for the quick reply @nixsee . I found you via [this](https://forum.obsidian.md/t/knowledge-innovation-value-and-wisdom/5166/35) Obsidian forum post but couldn't seem to private message you there so messaged here instead. If you have other contact details please send them after clicking on either the Like or Dislike on any of the inner pages of my site e.g. the bottom of this [Human Needs](https://reevolution.earth/kb/human-needs/)?

From reading your replies on the above thread, I would really value your input on my site above in terms of what I have wrote so far and maybe future material if this is something that might interest you?

**Comment by nixsee** [comment]
@m0r4h3u5 I sent you a message on the obsidian forum yesterday. Perhaps you don't get notifications for that, so letting you know here.
